#!/bin/bash

echo "===== SYSTEM INFO ====="

echo
echo "Hostname: $(hostname)"
echo "User: $(whoami)"
echo "Date: $(date)"

echo
echo "---- CPU Load ----"
uptime

echo
echo "---- Memory Usage ----"
free -h

echo
echo "---- Disk Usage ----"
df -h /

echo
echo "---- Top 5 Processes ----"
ps -eo pid,comm,%cpu,%mem --sort=-%cpu | head -n 6
